# Generated by Django 5.2.11 on 2026-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistent_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
