# Generated by Django 5.2.11 on 2026-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_server", "0003_document_created_by_knowledgebase_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
