# Generated by Django 5.2.11 on 2026-04-15 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_server", "0005_knowledgebaseinvite_knowledgebasemember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chunk",
            options={"verbose_name": "Chunk", "verbose_name_plural": "Chunks"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="embedding",
            options={"verbose_name": "Embedding", "verbose_name_plural": "Embeddings"},
        ),
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={
                "verbose_name": "Knowledge base",
                "verbose_name_plural": "Knowledge bases",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgebaseinvite",
            options={
                "verbose_name": "Knowledge base invite",
                "verbose_name_plural": "Knowledge base invites",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgebasemember",
            options={
                "verbose_name": "Knowledge base member",
                "verbose_name_plural": "Knowledge base members",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="db_server_d_created_9c57de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["knowledge_base", "is_deleted", "created_at"],
                name="dbs_doc_kb_del_cr_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "index"),
                name="db_server_chunk_unique_document_index",
            ),
        ),
        migrations.AlterModelTable(
            name="chunk",
            table="db_server_chunk",
        ),
        migrations.AlterModelTable(
            name="document",
            table="db_server_document",
        ),
        migrations.AlterModelTable(
            name="embedding",
            table="db_server_embedding",
        ),
        migrations.AlterModelTable(
            name="knowledgebase",
            table="db_server_knowledgebase",
        ),
        migrations.AlterModelTable(
            name="knowledgebaseinvite",
            table="db_server_knowledgebase_invite",
        ),
        migrations.AlterModelTable(
            name="knowledgebasemember",
            table="db_server_knowledgebase_member",
        ),
    ]
