GROUP_TYPE_STANDARD = "standard"
GROUP_TYPE_HEAD_OF_DEPARTMENT = "head_of_department"
GROUP_TYPE_ADMIN = "admin"

GROUP_TYPE_CHOICES = [
    (GROUP_TYPE_STANDARD, "Standard"),
    (GROUP_TYPE_HEAD_OF_DEPARTMENT, "Head of department"),
    (GROUP_TYPE_ADMIN, "Admin"),
]

ACCESS_LEVEL_ADMIN = "admin"
ACCESS_LEVEL_1 = "1"
ACCESS_LEVEL_2 = "2"
ACCESS_LEVEL_3 = "3"
ACCESS_LEVEL_4 = "4"

ACCESS_LEVEL_CHOICES = [
    (ACCESS_LEVEL_ADMIN, "Admin"),
    (ACCESS_LEVEL_1, "1"),
    (ACCESS_LEVEL_2, "2"),
    (ACCESS_LEVEL_3, "3"),
    (ACCESS_LEVEL_4, "4"),
]

DEFAULT_GROUP_TYPE = GROUP_TYPE_STANDARD
DEFAULT_ACCESS_LEVEL = ACCESS_LEVEL_4
